name: habitat
channels:
  - aihabitat-nightly
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=1_gnu
  - attrs=20.3.0=pyhd3deb0d_0
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2021.5.25=h06a4308_1
  - certifi=2021.5.30=py36h06a4308_0
  - cloudpickle=1.6.0=py_0
  - cmake=3.14.0=h52cb24c_0
  - cycler=0.10.0=py_2
  - cytoolz=0.11.0=py36h7b6447c_0
  - dask-core=1.1.4=py36_1
  - expat=2.3.0=h2531618_2
  - ffmpeg=4.3.1=h3215721_1
  - freetype=2.10.4=h0708190_1
  - gitdb=4.0.7=pyhd8ed1ab_0
  - gitpython=3.1.14=pyhd8ed1ab_0
  - gmp=6.2.1=h58526e2_0
  - gnutls=3.6.13=h85f3911_1
  - headless=1.0=0
  - icu=67.1=he1b5a44_0
  - imageio=2.9.0=py_0
  - imageio-ffmpeg=0.4.3=pyhd8ed1ab_0
  - jpeg=9d=h36c2ea0_0
  - kiwisolver=1.3.1=py36h51d7077_0
  - krb5=1.18.2=h173b8e3_0
  - lame=3.100=h7f98852_1001
  - lcms2=2.12=hddcbb42_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libblas=3.9.0=8_openblas
  - libcblas=3.9.0=8_openblas
  - libcurl=7.71.1=h20c2e04_1
  - libedit=3.1.20210216=h27cfd23_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h2828fa1_19
  - libgfortran-ng=7.5.0=h14aa051_19
  - libgfortran4=7.5.0=h14aa051_19
  - libgomp=9.3.0=h2828fa1_19
  - libiconv=1.16=h516909a_0
  - liblapack=3.9.0=8_openblas
  - libllvm10=10.0.1=he513fc3_3
  - libopenblas=0.3.12=pthreads_hb3c22a3_1
  - libpng=1.6.37=h21135ba_2
  - libssh2=1.9.0=h1ba5d50_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.2.0=h85742a9_0
  - libwebp-base=1.2.0=h7f98852_2
  - libxcb=1.13=h7f98852_1003
  - lz4-c=1.9.2=he1b5a44_3
  - matplotlib-base=3.2.2=py36h5fdd944_1
  - ncurses=6.2=he6710b0_1
  - nettle=3.6=he412f7d_0
  - networkx=2.2=py36_1
  - numpy=1.19.5=py36h2aa4a07_1
  - olefile=0.46=pyh9f0ad1d_1
  - openh264=2.1.1=h8b12597_0
  - openssl=1.1.1k=h27cfd23_0
  - pip=21.0.1=py36h06a4308_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - python=3.6.13=hdb3f193_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.6=1_cp36m
  - pywavelets=1.1.1=py36h7b6447c_2
  - quaternion=2021.4.5.14.42.35=py36h8f6f2f9_0
  - readline=8.1=h27cfd23_0
  - rhash=1.4.1=h3c74f83_1
  - scikit-image=0.17.2=py36hd87012b_4
  - setuptools=52.0.0=py36h06a4308_0
  - six=1.15.0=pyh9f0ad1d_0
  - sqlite=3.35.4=hdfb4753_0
  - tifffile=2020.10.1=py36hdd07704_2
  - tk=8.6.10=hbc83047_0
  - toolz=0.11.1=pyhd3eb1b0_0
  - tornado=6.1=py36h8f6f2f9_1
  - tqdm=4.60.0=pyhd8ed1ab_0
  - wheel=0.36.2=pyhd3eb1b0_0
  - withbullet=1.0=0
  - x264=1!152.20180806=h14c3975_0
  - xorg-fixesproto=5.0=h7f98852_1002
  - xorg-inputproto=2.3.2=h7f98852_1002
  - xorg-kbproto=1.0.7=h7f98852_1002
  - xorg-libx11=1.6.12=h516909a_0
  - xorg-libxau=1.0.9=h7f98852_0
  - xorg-libxcursor=1.2.0=h516909a_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxfixes=5.0.3=h516909a_1004
  - xorg-libxi=1.7.10=h516909a_0
  - xorg-libxinerama=1.1.4=hf484d3e_1000
  - xorg-libxrandr=1.5.2=h516909a_1
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-randrproto=1.5.0=h516909a_1001
  - xorg-renderproto=0.11.1=h7f98852_1002
  - xorg-xextproto=7.3.0=h7f98852_1002
  - xorg-xproto=7.0.31=h7f98852_1007
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==0.12.0
    - astor==0.8.1
    - braceexpand==0.1.6
    - cached-property==1.5.2
    - cachetools==4.2.1
    - chardet==4.0.0
    - click==7.1.2
    - dataclasses==0.8
    - decorator==4.4.2
    - future==0.18.2
    - gast==0.4.0
    - gnupg==2.3.1
    - google-auth==1.29.0
    - google-auth-oauthlib==0.4.4
    - grpcio==1.37.0
    - gym==0.18.0
    - h5py==3.1.0
    - habitat==0.1.7
    - habitat-sim==0.1.7
    - idna==2.10
    - ifcfg==0.21
    - importlib-metadata==4.0.0
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.2
    - llvmlite==0.36.0
    - lmdb==1.2.0
    - markdown==3.3.4
    - matplotlib==3.3.4
    - mock==4.0.3
    - moviepy==1.0.3
    - msgpack==1.0.2
    - numba==0.53.1
    - oauthlib==3.1.0
    - objectio==0.2.29
    - pickle5==0.0.11
    - pillow==7.2.0
    - proglog==0.1.9
    - protobuf==3.15.8
    - psutil==5.8.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycryptodomex==3.10.1
    - pyglet==1.5.0
    - pyyaml==5.4.1
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7.2
    - scipy==1.5.4
    - simplejson==3.17.2
    - smmap==4.0.0
    - tb-nightly==2.5.0a20210417
    - tensorboard==1.13.1
    - tensorboard-data-server==0.6.0
    - tensorboard-plugin-wit==1.8.0
    - tensorflow==1.13.1
    - tensorflow-estimator==1.13.0
    - termcolor==1.1.0
    - torch==1.8.1
    - typer==0.3.2
    - typing-extensions==3.7.4.3
    - urllib3==1.26.4
    - webdataset==0.1.40
    - werkzeug==1.0.1
    - yacs==0.1.8
    - zipp==3.4.1
prefix: /home/RozDavid/anaconda3/envs/habitat
