name: semantic_mapping
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _tflow_select=2.1.0
  - apr=1.6.5
  - argon2-cffi=20.1.0
  - astroid=2.3.2
  - async_generator=1.10
  - backcall=0.2.0
  - binutils_impl_linux-64=2.31.1
  - binutils_linux-64=2.31.1
  - blas=1.0
  - bleach=3.3.0
  - boost-cpp=1.70.0
  - bzip2=1.0.8
  - c-ares=1.17.1
  - ca-certificates=2021.1.19
  - catkin_pkg=0.4.23
  - certifi=2020.12.5
  - cffi=1.13.1
  - cloudpickle=1.2.2
  - cmake=3.16.3
  - console_bridge=1.0.1
  - coverage=5.5
  - cudatoolkit=10.1.243
  - cudnn=7.6.5
  - cupti=10.1.168
  - cycler=0.10.0
  - cython=0.29.22
  - cytoolz=0.10.1
  - dask-core=2.7.0
  - dbus=1.13.12
  - decorator=4.4.1
  - defusedxml=0.6.0
  - distro=1.5.0
  - docutils=0.16
  - empy=3.3.4
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - glib=2.56.2
  - gmock=1.10.0
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gtest=1.10.0
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - h5py=2.9.0
  - hdf5=1.10.4
  - icu=58.2
  - ignite=0.2.1
  - imageio=2.6.1
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2019.4
  - ipykernel=5.3.4
  - ipython=7.20.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.6.3
  - isort=4.3.21
  - jedi=0.17.0
  - jinja2=2.11.3
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.7.1
  - jupyterlab_pygments=0.1.2
  - jupyterlab_widgets=1.0.0
  - keras=2.3.1
  - keras-applications=1.0.8
  - kiwisolver=1.1.0
  - krb5=1.17.1
  - lazy-object-proxy=1.4.2
  - libapr=1.6.5
  - libapriconv=1.2.2
  - libaprutil=1.6.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libedit=3.1.20181209
  - libev=4.33
  - libffi=3.2.1
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libgpuarray=0.7.6
  - libiconv=1.16
  - liblapack=3.8.0
  - libnghttp2=1.41.0
  - libpng=1.6.37
  - libprotobuf=3.9.2
  - libsodium=1.0.18
  - libssh2=1.9.0
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libuv=1.40.0
  - libxcb=1.13
  - libxml2=2.9.9
  - log4cxx=0.10.0
  - mako=1.1.4
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.3.0
  - mkl_fft=1.0.14
  - mkl_random=1.1.0
  - mock=4.0.1
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.1.2
  - ncurses=6.1
  - nest-asyncio=1.4.3
  - netifaces=0.10.9
  - networkx=2.4
  - ninja=1.9.0
  - nose=1.3.7
  - notebook=6.2.0
  - numpy=1.17.2
  - numpy-base=1.17.2
  - olefile=0.46
  - openssl=1.1.1k
  - packaging=20.9
  - pandas=0.25.3
  - pandoc=2.11
  - pandocfilters=1.4.3
  - parso=0.8.1
  - pcre=8.43
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=6.0.0
  - pip=21.0.1
  - pkg-config=0.29.2
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - ptyprocess=0.7.0
  - pycparser=2.19
  - pygments=2.7.4
  - pygpu=0.7.6
  - pylint=2.4.3
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - python=3.7.5
  - python-dateutil=2.8.0
  - python_abi=3.7
  - pytorch=1.3.1
  - pytz=2019.3
  - pywavelets=1.1.1
  - pyyaml=5.4.1
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - readline=7.0
  - rhash=1.4.0
  - ros-catkin=0.7.17
  - ros-conda-base=0.0.2
  - ros-conda-mutex=1.0
  - ros-cpp-common=0.6.12
  - ros-environment=1.2.1
  - ros-gencpp=0.6.2
  - ros-geneus=2.2.6
  - ros-genlisp=0.4.16
  - ros-genmsg=0.5.12
  - ros-gennodejs=2.0.1
  - ros-genpy=0.6.8
  - ros-message-generation=0.4.0
  - ros-message-runtime=0.4.12
  - ros-rosbuild=1.14.6
  - ros-rosconsole=1.13.10
  - ros-roscpp=1.14.3
  - ros-roscpp-serialization=0.6.12
  - ros-roscpp-traits=0.6.12
  - ros-rosgraph=1.14.3
  - ros-rosgraph-msgs=1.11.2
  - ros-roslib=1.14.6
  - ros-rospack=2.5.3
  - ros-rospy=1.14.3
  - ros-rostime=0.6.12
  - ros-std-msgs=0.5.12
  - ros-xmlrpcpp=1.14.3
  - rosdep=0.20.0
  - rosdistro=0.8.3
  - rospkg=1.2.9
  - scikit-image=0.14.2
  - scipy=1.2.1
  - send2trash=1.5.0
  - setuptools=41.6.0
  - sip=4.19.8
  - six=1.12.0
  - sqlite=3.30.1
  - tensorboard=1.14.0
  - tensorboardx=1.9
  - tensorflow=1.14.0
  - tensorflow-base=1.14.0
  - tensorflow-estimator=1.14.0
  - tensorflow-gpu=1.14.0
  - termcolor=1.1.0
  - terminado=0.9.2
  - testpath=0.4.4
  - theano=1.0.5
  - tinyxml2=8.0.0
  - tk=8.6.8
  - toolz=0.10.0
  - torchvision=0.4.2
  - tornado=6.0.3
  - tqdm=4.36.1
  - traitlets=5.0.5
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.33.6
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - xz=5.2.4
  - yaml=0.2.5
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.8.1
    - appdirs==1.4.4
    - astor==0.8.0
    - attrs==19.3.0
    - chardet==3.0.4
    - cityscapesscripts==1.5.0
    - dill==0.3.1.1
    - freetype-py==2.2.0
    - future==0.18.2
    - gast==0.2.2
    - google-pasta==0.1.8
    - googleapis-common-protos==1.6.0
    - grpcio==1.25.0
    - idna==2.8
    - keras-preprocessing==1.1.0
    - markdown==3.1.1
    - netron==4.8.6
    - onnx==1.6.0
    - onnxruntime==1.0.0
    - opencv-python==3.4.3.18
    - opt-einsum==3.1.0
    - promise==2.3
    - protobuf==3.10.0
    - pyglet==1.5.15
    - pyopengl==3.1.0
    - pyrender==0.1.45
    - trimesh==3.9.12
    - typing-extensions==3.7.4.1
prefix: /home/RozDavid/anaconda3/envs/semantic_mapping
