name: semantic_mapping
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - apr=1.6.5=h516909a_2
  - argon2-cffi=20.1.0=py37h7b6447c_1
  - astroid=2.3.2=py37_0
  - async_generator=1.10=py37h28b3542_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - binutils_impl_linux-64=2.31.1=h6176602_1
  - binutils_linux-64=2.31.1=h6176602_9
  - blas=1.0=mkl
  - bleach=3.3.0=pyhd3eb1b0_0
  - boost-cpp=1.70.0=ha2d47e9_1
  - bzip2=1.0.8=h516909a_3
  - c-ares=1.17.1=h36c2ea0_0
  - ca-certificates=2021.1.19=h06a4308_1
  - catkin_pkg=0.4.23=pyh9f0ad1d_0
  - certifi=2020.12.5=py37h06a4308_0
  - cffi=1.13.1=py37h2e261b9_0
  - cloudpickle=1.2.2=py_0
  - cmake=3.16.3=h28c56e5_0
  - console_bridge=1.0.1=hc9558a2_0
  - coverage=5.5=py37h27cfd23_2
  - cudatoolkit=10.1.243=h6bb024c_0
  - cudnn=7.6.5=cuda10.1_0
  - cupti=10.1.168=0
  - cycler=0.10.0=py37_0
  - cython=0.29.22=py37h2531618_0
  - cytoolz=0.10.1=py37h516909a_0
  - dask-core=2.7.0=py_0
  - dbus=1.13.12=h746ee38_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - distro=1.5.0=pyh9f0ad1d_0
  - docutils=0.16=py37h89c1867_3
  - empy=3.3.4=pyh9f0ad1d_1
  - entrypoints=0.3=py37_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - gcc_impl_linux-64=7.3.0=habb00fd_1
  - gcc_linux-64=7.3.0=h553295d_9
  - glib=2.56.2=hd408876_0
  - gmock=1.10.0=ha770c72_5
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - gtest=1.10.0=h0efe328_4
  - gxx_impl_linux-64=7.3.0=hdf63c60_1
  - gxx_linux-64=7.3.0=h553295d_9
  - h5py=2.9.0=py37h7918eee_0
  - hdf5=1.10.4=hb1b8bf9_0
  - icu=58.2=h9c2bf20_1
  - ignite=0.2.1=py37_0
  - imageio=2.6.1=py37_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - intel-openmp=2019.4=243
  - ipykernel=5.3.4=py37h5ca1d4c_0
  - ipython=7.20.0=py37hb070fc8_1
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - ipywidgets=7.6.3=pyhd3eb1b0_1
  - isort=4.3.21=py37_0
  - jedi=0.17.0=py37_0
  - jinja2=2.11.3=pyhd3eb1b0_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.2.0=py_2
  - jupyter=1.0.0=py37_7
  - jupyter_client=6.1.7=py_0
  - jupyter_console=6.2.0=py_0
  - jupyter_core=4.7.1=py37h06a4308_0
  - jupyterlab_pygments=0.1.2=py_0
  - jupyterlab_widgets=1.0.0=pyhd3eb1b0_1
  - keras=2.3.1=py37_0
  - keras-applications=1.0.8=py_1
  - kiwisolver=1.1.0=py37he6710b0_0
  - krb5=1.17.1=h173b8e3_0
  - lazy-object-proxy=1.4.2=py37h7b6447c_0
  - libapr=1.6.5=h516909a_2
  - libapriconv=1.2.2=h516909a_2
  - libaprutil=1.6.1=ha1d75be_1
  - libblas=3.8.0=14_mkl
  - libcblas=3.8.0=14_mkl
  - libcurl=7.71.1=hcdd3856_8
  - libedit=3.1.20181209=hc058e9b_0
  - libev=4.33=h516909a_1
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libgpuarray=0.7.6=h14c3975_1003
  - libiconv=1.16=h516909a_0
  - liblapack=3.8.0=14_mkl
  - libnghttp2=1.41.0=h8cfc5f6_2
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.9.2=hd408876_0
  - libsodium=1.0.18=h7b6447c_0
  - libssh2=1.9.0=hab1572f_5
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_0
  - libuuid=1.0.3=h1bed415_2
  - libuv=1.40.0=hd18ef5c_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - log4cxx=0.10.0=h66fa5af_1
  - mako=1.1.4=pyh44b312d_0
  - markupsafe=1.1.1=py37h14c3975_1
  - matplotlib=3.1.1=py37h5429711_0
  - mccabe=0.6.1=py37_1
  - mistune=0.8.4=py37h14c3975_1001
  - mkl=2019.4=243
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.0.14=py37ha843d7b_0
  - mkl_random=1.1.0=py37hd6b4f25_0
  - mock=4.0.1=py_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py37_0
  - nbformat=5.1.2=pyhd3eb1b0_1
  - ncurses=6.1=he6710b0_1
  - nest-asyncio=1.4.3=pyhd3eb1b0_0
  - netifaces=0.10.9=py37h8f50634_1003
  - networkx=2.4=py_0
  - ninja=1.9.0=py37hfd86e86_0
  - nose=1.3.7=py_1006
  - notebook=6.2.0=py37h06a4308_0
  - numpy=1.17.2=py37haad9e8e_0
  - numpy-base=1.17.2=py37hde5b4d6_0
  - olefile=0.46=py37_0
  - openssl=1.1.1k=h27cfd23_0
  - packaging=20.9=pyhd3eb1b0_0
  - pandas=0.25.3=py37he6710b0_0
  - pandoc=2.11=hb0f4dca_0
  - pandocfilters=1.4.3=py37h06a4308_1
  - parso=0.8.1=pyhd3eb1b0_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.8.0=pyhd3eb1b0_3
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=6.0.0=py37h34e0f95_0
  - pip=21.0.1=py37h06a4308_0
  - pkg-config=0.29.2=h36c2ea0_1008
  - prometheus_client=0.9.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.8=py_0
  - prompt_toolkit=3.0.8=0
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pycparser=2.19=py37_0
  - pygments=2.7.4=pyhd3eb1b0_0
  - pygpu=0.7.6=py37h161383b_1002
  - pylint=2.4.3=py37_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py37h05f1152_2
  - pyrsistent=0.17.3=py37h7b6447c_0
  - python=3.7.5=h0371630_0
  - python-dateutil=2.8.0=py37_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.3.1=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pytz=2019.3=py_0
  - pywavelets=1.1.1=py37hc1659b7_0
  - pyyaml=5.4.1=py37h27cfd23_1
  - pyzmq=20.0.0=py37h2531618_1
  - qt=5.9.7=h5867ecd_1
  - qtconsole=4.7.7=py_0
  - qtpy=1.9.0=py_0
  - readline=7.0=h7b6447c_5
  - rhash=1.4.0=h36c2ea0_0
  - ros-catkin=0.7.17=py37h3340039_5
  - ros-conda-base=0.0.2=hcb32578_2
  - ros-conda-mutex=1.0=melodic
  - ros-cpp-common=0.6.12=py37he1b5a44_2
  - ros-environment=1.2.1=py37h3340039_2
  - ros-gencpp=0.6.2=py37h3340039_1
  - ros-geneus=2.2.6=py37h3340039_1
  - ros-genlisp=0.4.16=py37h3340039_1
  - ros-genmsg=0.5.12=py37h3340039_1
  - ros-gennodejs=2.0.1=py37h3340039_1
  - ros-genpy=0.6.8=py37h3340039_1
  - ros-message-generation=0.4.0=h3340039_1
  - ros-message-runtime=0.4.12=he1b5a44_0
  - ros-rosbuild=1.14.6=he1b5a44_0
  - ros-rosconsole=1.13.10=h8b68381_0
  - ros-roscpp=1.14.3=py37h8b68381_2
  - ros-roscpp-serialization=0.6.12=he1b5a44_0
  - ros-roscpp-traits=0.6.12=he1b5a44_0
  - ros-rosgraph=1.14.3=py37h3340039_1
  - ros-rosgraph-msgs=1.11.2=py37h3340039_1
  - ros-roslib=1.14.6=py37heaf0793_4
  - ros-rospack=2.5.3=py37h8b68381_0
  - ros-rospy=1.14.3=py37h3340039_1
  - ros-rostime=0.6.12=h8b68381_0
  - ros-std-msgs=0.5.12=py37h3340039_1
  - ros-xmlrpcpp=1.14.3=he1b5a44_0
  - rosdep=0.20.0=py37h89c1867_0
  - rosdistro=0.8.3=py37h89c1867_2
  - rospkg=1.2.9=pyhd3deb0d_0
  - scikit-image=0.14.2=py37hf484d3e_0
  - scipy=1.2.1=py37h09a28d5_1
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=41.6.0=py37_0
  - sip=4.19.8=py37hf484d3e_0
  - six=1.12.0=py37_0
  - sqlite=3.30.1=h7b6447c_0
  - tensorboard=1.14.0=py37hf484d3e_0
  - tensorboardx=1.9=py_0
  - tensorflow=1.14.0=gpu_py37h74c33d7_0
  - tensorflow-base=1.14.0=gpu_py37he45bfe2_0
  - tensorflow-estimator=1.14.0=py_0
  - tensorflow-gpu=1.14.0=h0d30ee6_0
  - termcolor=1.1.0=py37h06a4308_1
  - terminado=0.9.2=py37h06a4308_0
  - testpath=0.4.4=pyhd3eb1b0_0
  - theano=1.0.5=py37h745909e_1
  - tinyxml2=8.0.0=he1b5a44_1
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - torchvision=0.4.2=py37_cu101
  - tornado=6.0.3=py37h7b6447c_0
  - tqdm=4.36.1=py_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py37_1
  - werkzeug=1.0.1=pyhd3eb1b0_0
  - wheel=0.33.6=py37_0
  - widgetsnbextension=3.5.1=py37_0
  - wrapt=1.11.2=py37h7b6447c_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.3=he6710b0_3
  - zipp=3.4.0=pyhd3eb1b0_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pip:
    - absl-py==0.8.1
    - appdirs==1.4.4
    - astor==0.8.0
    - attrs==19.3.0
    - chardet==3.0.4
    - cityscapesscripts==1.5.0
    - dill==0.3.1.1
    - freetype-py==2.2.0
    - future==0.18.2
    - gast==0.2.2
    - google-pasta==0.1.8
    - googleapis-common-protos==1.6.0
    - grpcio==1.25.0
    - idna==2.8
    - keras-preprocessing==1.1.0
    - markdown==3.1.1
    - netron==4.8.6
    - onnx==1.6.0
    - onnxruntime==1.0.0
    - opencv-python==3.4.3.18
    - opt-einsum==3.1.0
    - promise==2.3
    - protobuf==3.10.0
    - pyglet==1.5.15
    - pyopengl==3.1.0
    - pyrender==0.1.45
    - trimesh==3.9.12
    - typing-extensions==3.7.4.1
prefix: /home/RozDavid/anaconda3/envs/semantic_mapping